### PR TITLE
Formalize standard_kaldi RPC

### PR DESCRIPTION
**Pull request by maxhawkins**
False alarm—I was worried that the new RPC was buggy but the issue was outside of Gentle so I reverted my earlier PR. I added some tests and now I'm more confident in the new code.

This PR undoes the revert and adds a few tests.

### CODE REVIEW

**Comment by maxhawkins** [comment]
I just fixed the build. Please take a look.

**Comment by strob** [comment]
Can you explain in a sentence or two what this PR provides to Gentle or what you hope that moving in this direction will enable? If I'm not mistaken, this looks like a direction that would eventually allow for more efficient behavior in the case of multiple simultaneous transcriptions (especially with a large language model), but as far as I can tell there are no performance improvements as yet.

**Comment by maxhawkins** [comment]
This is a digestible chunk from a larger refactor that includes performance improvements like multiprocessing with BSD sockets. Its main purpose is making the communication protocol between std_kaldi and Python easier to understand.

During development I was slowed down by my incomplete understanding of this communication protocol. Making it explicit will make it easier for new developers to understand, easier to test, and easier to extend. It also extends the protocol with clear ways to handle errors and arbitrary blobs of binary data (like audio).

**Comment by maxhawkins** [comment]
thx

**Pull request merged**
