### PR TITLE
Unify status.html and view_alignment.html

### PR DESCRIPTION
**Pull request by maxhawkins**

### CODE REVIEW

**Comment by strob** [comment]
This is lovely!

It's a big usability enhancement, so I merged it. However, two things that should be fixed:

* The ```async=false``` flag in the ```TranscriptionsController``` should still run ```transcribe``` in a thread and return ```NOT_DONE_YET```. Otherwise twisted will block, and the entire web app will be down when someone is transcribing synchronously. I can help you with this if you'd like.

* Also related to ```async=false```, we should not run the ```diff_align``` stage after every chunk, as that's unnecessarily computationally intensive.

**Comment by maxhawkins** [comment]
Ah, that is not what I expected at all. What a confusing concurrency model.
I'll do a fix for that today.

I'll open a separate issue for the async=false speed up.

**Comment by strob** [comment]
It's actually a very simple concurrency model (the twisted main loop is synchronous), but from your last PR, I don't think you quite have a handle on it yet...
I'll make a patch.

**Comment by strob** [comment]
...it doesn't help that the redirect returns NOT_DONE_YET. That's really confusing.

**Pull request merged**
