### PR TITLE
TranscriptionController: separate async from sync code

### PR DESCRIPTION
**Pull request by maxhawkins**
Let me know if this still works or if I messed up the concurrency model again. I think this approach will be much easier to maintain.

### CODE REVIEW

**Comment by strob** [comment]
You're close, but the ```req.notifyFinish().addErrback``` was important; that flow needs to stay in.

**Comment by maxhawkins** [comment]
OK I'll fix

**Comment by maxhawkins** [comment]
Even better: we can cancel the thread. How does this look?

**Comment by maxhawkins** [comment]
OK I did some reading and now I understand how Twisted works. This code will work and I wrote some unit tests. I think the unit tests may have found a bug in the old implementation too!

**Comment by maxhawkins** [comment]
Also—did you know that it's possible to substitute the default reactor for a qt-specific one? Might be worth looking into for the packaged app.

**Comment by maxhawkins** [comment]
Hey does this look OK to you? I think it will be really useful to have these unit tests running.

**Comment by strob** [comment]
This looks great! Thanks so much (and sorry this merge took so long).

**Pull request merged**
