### PR TITLE
k3 with cuda

### PR DESCRIPTION
**Pull request by rakeshshrestha31**
Linking k3 executables with cuda libraries

### CODE REVIEW

**Comment by strob** [comment]
Interesting! What are the performance gains of doing this?

**Comment by rakeshshrestha31** [comment]
@strob  The example script [examples/gentle_curl.sh](https://github.com/lowerquality/gentle/blob/master/examples/gentle_curl.sh) takes between 14-15 seconds with cuda and 17-18 seconds without cuda. Ran the script for a few times using ubuntu's [time](http://manpages.ubuntu.com/manpages/trusty/man1/time.1.html) command.

**Comment by strob** [comment]
Well, it's something! Thanks for your contribution.

**Comment by rakeshshrestha31** [comment]
You're welcome :). 
Forgot to commit the k3.cc file. Another PR coming soon.

**Pull request merged**
