### PR TITLE
gentle css tweaks; makes the text easier to read

### PR DESCRIPTION
**Pull request by maxhawkins**

### CODE REVIEW

**Comment by strob** [comment]
This is bordering on being almost *too* slick, but I will merge. The only issue here is that the download links disappear when the window gets too small. I'd rather the &lt;audio&gt; element become smaller. I know the previous line-wrapping behavior wasn't pretty, but I prefer it to those elements simply vanishing. 

Tangent: is there really no way outside of a &lt;table&gt; to have that &lt;audio&gt; element fill all available space?

**Comment by maxhawkins** [comment]
I'm a little confused about the audio element too. I guess it's positioned relative in the shadow dom or something? It seems I can't give it a height. The real solution is just to build our own widget.

The links disappearing is an issue. I think the audio element has a min-height but maybe we can absolutely align the links and have them float over the audio. Another option is to add a second row to the menu bar when it gets too narrow.

**Comment by strob** [comment]
I would accept the links floating above the audio, going to a second line, a min-width in the &lt;body&gt; that adds horizontal scroll. The user should enlarge the window if it's too small, but they need to know to do so.

**Comment by maxhawkins** [comment]
Horizontal scrolling is really awkward on mobile. I'd rather do the second row. I'll work on this now...

**Comment by maxhawkins** [comment]
On second thought I think it makes more sense to either embed download links above or below the transcript and to leave the toolbar less cluttered or move the audio player to the bottom of the page.

In the meantime I'm just going to give the download links a background color. It's kind of a hack but will do the job for now.

**Comment by strob** [comment]
It's fine for now. I was also thinking about a zipfile download that gives the whole directory (would need to add an ```align.js``` for ```file:///``` compatibility), in which case the download links would probably need to be refactored, but this is a great start.

**Pull request merged**
