### PR TITLE
Easier server install

### PR DESCRIPTION
**Pull request by maxhawkins**
Some tweaks to the install scripts and server.py to make installation easier

### CODE REVIEW

**Comment by strob** [comment]
Kaldi still wants subversion installed for its dependencies. The Makefile in ```tools/``` calls ```extras/check_dependencies.sh```, which (L37) checks for subversion. That said, AFAICT the only actual use of svn is in  ```extras/install_irstlm.sh```, which is not installed by default. Still: installing subversion is simpler than patching Kaldi's Makefiles.

**Comment by strob** [comment]
I like all of this except for removing subversion. I have a slight preference for installing Twisted through apt instead of pip, but could be convinced if you have a good reason. Once those two points are addressed, I will merge.

**Comment by maxhawkins** [comment]
OK, nuked the subversion commit.

I think the setup.py approach makes sense for two reasons:

1. Homebrew doesn't manage Python dependencies. Any change to the Python deps will mean changing in two places. We will forget and this will cause bugs.
2. Specifying Python deps in a shell script goes against the grain of the Python community. Most open-source Python projects have a setup.py. If we ever want to use distutils or py2app we'll need one anyway.

**Comment by strob** [comment]
OK, thanks for addressing subversion! I've merged this for now and we'll see how it goes. OS X ships with Twisted, which we will unnecessarily be overwriting with pip, but unless that causes any problems it doesn't bother me. I'm working on a setup.py for py2app in another branch, so yes, that's good to have.

**Comment by maxhawkins** [comment]
I'm pretty sure Twisted isn't pre-installed anymore (at least it wasn't on my machine). Always good to have the latest version anyway.

**Pull request merged**
