### PR TITLE
UX Tweaks

### PR DESCRIPTION
**Pull request by maxhawkins**

### CODE REVIEW

**Comment by strob** [comment]
I will merge this once the "submit" button has the ```cursor:pointer;``` style (it no longer resembles a standard button, so hover should reflect clickability).

That said, keep in mind that there is cost to beauty. Every line of code added to this UI--which really should be thought of as an demo/example/reference implementation, not a fully-formed application--obscures just that much more the function and legibility of the code. "Less is more."

**Comment by maxhawkins** [comment]
Point taken. I'm not planning to go overboard here.

There's also something to be said for shininess. First impressions count!

**Comment by strob** [comment]
I accidentally did a partial merge earlier. b5a5b3fc24025fc17c6af6be3b197a6d4447f1c4 is the latest patch.

**Comment by maxhawkins** [comment]
That's OK I'll do a rebase

**Comment by maxhawkins** [comment]
Oh I see you merged rather than rebasing. I'll delete the branch then.

**Pull request closed without merging**
