### PR TITLE
Add Docker Build

### PR DESCRIPTION
**Pull request by maxhawkins**
Add a Dockerfile that builds everything and runs the web service by default

Just run this:

```
docker build -t lowerquality/gentle .
docker run -p 8765:8765 lowerquality/gentle 
```

It also adds a [Travis CI](https://travis-ci.org) build that will automatically build everything from scratch tell us if our tests failed. If you have a chance try logging into Travis and enabling the build.

We should also register for the Docker hub and publish a stable image when when hit 1.0. That will make installation as easy as typing `docker run -p 8765:8765 lowerquality/gentle` for people already running Docker.

### CODE REVIEW

**Comment by maxhawkins** [comment]
I haven't gotten it to build on Travis quite yet, but this latest change should fix it. The build takes about 20m total:

https://travis-ci.org/maxhawkins/gentle/builds

**Comment by strob** [comment]
I still think this lucier test is questionable; an alignment ratio would seem like a better way to watch out for alignment regressions.

**Comment by maxhawkins** [comment]
Totally agree—that test is brittle. It's just a placeholder until something more sophisticated gets written.

I'm still not sure whether the regression has to do with numerical instability or some configuration error. I was able to get an exact match the last time I tried to dockerize so I think it might mean there's a bug.

**Comment by maxhawkins** [comment]
Could you enable Travis on lowerquality/gentle? It would be nice to have continuous integration for the master branch.

**Pull request merged**
