### PR TITLE
Merge mkgraph and standard_kaldi

### PR DESCRIPTION
**Pull request by maxhawkins**
Now you just have to send a make-model message to standard_kaldi with the text FST in the body.

### CODE REVIEW

**Comment by strob** [comment]
I'm having problems with this when running from the GUI. Does this error mean something to you?

```
GATORADE:gentle rmo$ python gentle.py 
Exception IOError: IOError('Lost connection with standard_kaldi subprocess',) in <bound method Kaldi.__del__ of <gentle.standard_kaldi.Kaldi object at 0x105bad490>> ignored
Unhandled error in Deferred:


Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/Library/Python/2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/Library/Python/2.7/site-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/Library/Python/2.7/site-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/Library/Python/2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Library/Python/2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/Users/rmo/src/gentle/serve.py", line 93, in transcribe
    for result in progress:
  File "/Users/rmo/src/gentle/gentle/language_model_transcribe.py", line 55, in lm_transcribe_progress
    k.stop()
  File "/Users/rmo/src/gentle/gentle/standard_kaldi.py", line 66, in stop
    self.rpc.do('stop')
  File "/Users/rmo/src/gentle/gentle/rpc.py", line 22, in do
    self._write_request(method, args, body)
  File "/Users/rmo/src/gentle/gentle/rpc.py", line 43, in _write_request
    raise IOError("Lost connection with standard_kaldi subprocess")
exceptions.IOError: Lost connection with standard_kaldi subprocess```

**Comment by maxhawkins** [comment]
This means the C++ code is throwing (and not catching) an exception. Can you log the subprocess's stderr to see the exception?

**Comment by strob** [comment]
So far I haven't managed to get a better log, but I have been able to reliably reproduce this error by attempting two simultaneous transcriptions.

This problem is also present on ```serve.py```, though I don't see an error reported at all. If you run ```sh tests/sync_test.sh``` twice, the second will never return.

I've tested MASTER, and this is not a problem.

**Comment by strob** [comment]
I can't find any relationship between this patch and threading considerations. Do you have any ideas why I'm seeing this behavior? Are you able to reproduce this, or do multiple simultaneous alignments work for you?

**Comment by maxhawkins** [comment]
Looks like I need to do more testing. I'll reply when I have some fixes.

**Pull request closed without merging**
